module.exports = {
  '@components': './lib/components',
  '@config': './lib/config',
  '@data': './lib/data',
  '@db': './lib/db',
  '@fixtures': './lib/fixtures',
  '@forms': './lib/forms',
  '@hooks': './lib/hooks',
  '@images': './lib/images',
  '@model': './lib/model',
  '@root': './lib',
  '@screens': './lib/screens',
  '@services': './lib/services',
  '@store': './lib/store',
  '@structure': './lib/structure',
  '@styles': './lib/styles',
  '@templates': './lib/templates',
  '@translations': './lib/translations',
  '@types': './types',
  '@ui-elements': './lib/ui-elements',
  '@utils': './lib/utils',
}
