// flow-typed signature: 6a482a17144d23b2634a286e4140b099
// flow-typed version: <<STUB>>/babel-plugin-dotenv-import_v^2.1.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-dotenv-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-dotenv-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/as-alias/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/blacklist/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/custom-module/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/default-import/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/default/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/filename/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/from-env/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/safe-error/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/safe-no-dotenv/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/safe-success/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/undefined/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/unused/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/variable-not-exist/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/whitelist/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/wildcard-import/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/__tests__/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/as-alias/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/__fixtures__/as-alias/source'>;
}
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/blacklist/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/__fixtures__/blacklist/source'>;
}
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/custom-module/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/__fixtures__/custom-module/source'>;
}
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/default-import/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/__fixtures__/default-import/source'>;
}
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/default/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/__fixtures__/default/source'>;
}
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/filename/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/__fixtures__/filename/source'>;
}
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/from-env/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/__fixtures__/from-env/source'>;
}
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/safe-error/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/__fixtures__/safe-error/source'>;
}
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/safe-no-dotenv/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/__fixtures__/safe-no-dotenv/source'>;
}
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/safe-success/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/__fixtures__/safe-success/source'>;
}
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/undefined/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/__fixtures__/undefined/source'>;
}
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/unused/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/__fixtures__/unused/source'>;
}
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/variable-not-exist/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/__fixtures__/variable-not-exist/source'>;
}
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/whitelist/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/__fixtures__/whitelist/source'>;
}
declare module 'babel-plugin-dotenv-import/__tests__/__fixtures__/wildcard-import/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/__fixtures__/wildcard-import/source'>;
}
declare module 'babel-plugin-dotenv-import/__tests__/index.test.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/__tests__/index.test'>;
}
declare module 'babel-plugin-dotenv-import/index' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import'>;
}
declare module 'babel-plugin-dotenv-import/index.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import'>;
}
