// flow-typed signature: 60dbc6a7f557868db2f9ebf99de25fd7
// flow-typed version: <<STUB>>/md5-hex_v^3.0.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'md5-hex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'md5-hex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'md5-hex/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'md5-hex/browser.js' {
  declare module.exports: $Exports<'md5-hex/browser'>;
}
declare module 'md5-hex/index' {
  declare module.exports: $Exports<'md5-hex'>;
}
declare module 'md5-hex/index.js' {
  declare module.exports: $Exports<'md5-hex'>;
}
