// flow-typed signature: fb9ca684c88fad6e37271d667a6aecec
// flow-typed version: <<STUB>>/postinstall-postinstall_v^2.1.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postinstall-postinstall'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postinstall-postinstall' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postinstall-postinstall/run' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postinstall-postinstall/run.js' {
  declare module.exports: $Exports<'postinstall-postinstall/run'>;
}
