// flow-typed signature: de594082ca9ab903dcb29fa2a318b755
// flow-typed version: <<STUB>>/react-native-popup-menu_v^0.15.9/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-popup-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-popup-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-popup-menu/build/rnpm' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/rollup.config.babel' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/setup-jasmine-env' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/Backdrop' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/constants' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/helpers' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/logger' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/Menu' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/MenuOption' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/MenuOptions' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/MenuPlaceholder' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/MenuProvider' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/menuRegistry' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/MenuTrigger' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/polyfills' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/renderers/ContextMenu' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/renderers/MenuOutside' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/renderers/NotAnimatedContextMenu' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/renderers/Popover' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/renderers/SlideInMenu' {
  declare module.exports: any;
}

declare module 'react-native-popup-menu/src/with-context' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-popup-menu/build/rnpm.js' {
  declare module.exports: $Exports<'react-native-popup-menu/build/rnpm'>;
}
declare module 'react-native-popup-menu/rollup.config.babel.js' {
  declare module.exports: $Exports<'react-native-popup-menu/rollup.config.babel'>;
}
declare module 'react-native-popup-menu/setup-jasmine-env.js' {
  declare module.exports: $Exports<'react-native-popup-menu/setup-jasmine-env'>;
}
declare module 'react-native-popup-menu/src/Backdrop.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/Backdrop'>;
}
declare module 'react-native-popup-menu/src/constants.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/constants'>;
}
declare module 'react-native-popup-menu/src/helpers.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/helpers'>;
}
declare module 'react-native-popup-menu/src/index' {
  declare module.exports: $Exports<'react-native-popup-menu/src'>;
}
declare module 'react-native-popup-menu/src/index.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src'>;
}
declare module 'react-native-popup-menu/src/logger.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/logger'>;
}
declare module 'react-native-popup-menu/src/Menu.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/Menu'>;
}
declare module 'react-native-popup-menu/src/MenuOption.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/MenuOption'>;
}
declare module 'react-native-popup-menu/src/MenuOptions.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/MenuOptions'>;
}
declare module 'react-native-popup-menu/src/MenuPlaceholder.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/MenuPlaceholder'>;
}
declare module 'react-native-popup-menu/src/MenuProvider.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/MenuProvider'>;
}
declare module 'react-native-popup-menu/src/menuRegistry.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/menuRegistry'>;
}
declare module 'react-native-popup-menu/src/MenuTrigger.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/MenuTrigger'>;
}
declare module 'react-native-popup-menu/src/polyfills.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/polyfills'>;
}
declare module 'react-native-popup-menu/src/renderers/ContextMenu.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/renderers/ContextMenu'>;
}
declare module 'react-native-popup-menu/src/renderers/MenuOutside.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/renderers/MenuOutside'>;
}
declare module 'react-native-popup-menu/src/renderers/NotAnimatedContextMenu.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/renderers/NotAnimatedContextMenu'>;
}
declare module 'react-native-popup-menu/src/renderers/Popover.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/renderers/Popover'>;
}
declare module 'react-native-popup-menu/src/renderers/SlideInMenu.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/renderers/SlideInMenu'>;
}
declare module 'react-native-popup-menu/src/with-context.js' {
  declare module.exports: $Exports<'react-native-popup-menu/src/with-context'>;
}
