// flow-typed signature: c3c24495575a6e950237515f33f60140
// flow-typed version: <<STUB>>/react-native-reanimated_v^1.10.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-reanimated'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-reanimated' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-reanimated/lib/commonjs/__mocks__/ReanimatedEventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/__mocks__/ReanimatedModule.native' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/Animated' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/Animated.test' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/animations/Animation' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/animations/backwardCompatibleAnimWrapper' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/animations/decay' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/animations/spring' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/animations/SpringUtils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/animations/timing' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/base' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/ConfigHelper' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/__mocks__/AnimatedProps' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedAlways' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedBezier' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedBlock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedCall' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedCallFunc' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedClock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedClockTest' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedCode' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedConcat' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedCond' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedDebug' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedEvent' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedFunction' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedNode' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedOperator' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedParam' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedProps' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedSet' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedStartClock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedStopClock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedStyle' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedTransform' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/AnimatedValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/Core.test' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/createEventObjectProxyPolyfill' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/core/InternalAnimatedValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/createAnimatedComponent' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/derived/__mocks__/evaluateOnce' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/derived/acc' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/derived/color' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/derived/diff' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/derived/diffClamp' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/derived/evaluateOnce' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/derived' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/derived/interpolate' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/derived/interpolate.test' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/derived/interpolateColors' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/derived/onChange' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/derived/useCode' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/Easing' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/operators' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/ReanimatedEventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/ReanimatedModule' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/ReanimatedModule.macos' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/ReanimatedModule.native' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/ReanimatedModule.windows' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/ReanimatedModuleCompat' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/SpringConfig' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/Transitioning' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/useValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/commonjs/val' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/__mocks__/ReanimatedEventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/__mocks__/ReanimatedModule.native' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/Animated' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/Animated.test' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/animations/Animation' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/animations/backwardCompatibleAnimWrapper' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/animations/decay' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/animations/spring' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/animations/SpringUtils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/animations/timing' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/base' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/ConfigHelper' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/__mocks__/AnimatedProps' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedAlways' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedBezier' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedBlock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedCall' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedCallFunc' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedClock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedClockTest' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedCode' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedConcat' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedCond' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedDebug' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedEvent' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedFunction' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedNode' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedOperator' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedParam' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedProps' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedSet' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedStartClock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedStopClock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedStyle' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedTransform' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/AnimatedValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/Core.test' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/createEventObjectProxyPolyfill' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/core/InternalAnimatedValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/createAnimatedComponent' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/derived/__mocks__/evaluateOnce' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/derived/acc' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/derived/color' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/derived/diff' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/derived/diffClamp' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/derived/evaluateOnce' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/derived' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/derived/interpolate' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/derived/interpolate.test' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/derived/interpolateColors' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/derived/onChange' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/derived/useCode' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/Easing' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/operators' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/ReanimatedEventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/ReanimatedModule' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/ReanimatedModule.macos' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/ReanimatedModule.native' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/ReanimatedModule.windows' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/ReanimatedModuleCompat' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/SpringConfig' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/Transitioning' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/useValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/module/val' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/mock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/__mocks__/ReanimatedEventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/__mocks__/ReanimatedModule.native' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/Animated' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/Animated.test' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/animations/Animation' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/animations/backwardCompatibleAnimWrapper' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/animations/decay' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/animations/spring' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/animations/SpringUtils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/animations/timing' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/base' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/ConfigHelper' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/__mocks__/AnimatedProps' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedAlways' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedBezier' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedBlock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedCall' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedCallFunc' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedClock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedClockTest' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedCode' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedConcat' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedCond' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedDebug' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedEvent' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedFunction' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedNode' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedOperator' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedParam' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedProps' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedSet' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedStartClock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedStopClock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedStyle' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedTransform' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/AnimatedValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/Core.test' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/createEventObjectProxyPolyfill' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/core/InternalAnimatedValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/createAnimatedComponent' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/derived/__mocks__/evaluateOnce' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/derived/acc' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/derived/color' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/derived/diff' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/derived/diffClamp' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/derived/evaluateOnce' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/derived' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/derived/interpolate' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/derived/interpolate.test' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/derived/interpolateColors' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/derived/onChange' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/derived/useCode' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/Easing' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/operators' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/ReanimatedEventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/ReanimatedModule' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/ReanimatedModule.macos' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/ReanimatedModule.native' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/ReanimatedModule.windows' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/ReanimatedModuleCompat' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/SpringConfig' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/Transitioning' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/useValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/val' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-reanimated/lib/commonjs/__mocks__/ReanimatedEventEmitter.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/__mocks__/ReanimatedEventEmitter'>;
}
declare module 'react-native-reanimated/lib/commonjs/__mocks__/ReanimatedModule.native.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/__mocks__/ReanimatedModule.native'>;
}
declare module 'react-native-reanimated/lib/commonjs/Animated.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/Animated'>;
}
declare module 'react-native-reanimated/lib/commonjs/Animated.test.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/Animated.test'>;
}
declare module 'react-native-reanimated/lib/commonjs/animations/Animation.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/animations/Animation'>;
}
declare module 'react-native-reanimated/lib/commonjs/animations/backwardCompatibleAnimWrapper.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/animations/backwardCompatibleAnimWrapper'>;
}
declare module 'react-native-reanimated/lib/commonjs/animations/decay.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/animations/decay'>;
}
declare module 'react-native-reanimated/lib/commonjs/animations/spring.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/animations/spring'>;
}
declare module 'react-native-reanimated/lib/commonjs/animations/SpringUtils.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/animations/SpringUtils'>;
}
declare module 'react-native-reanimated/lib/commonjs/animations/timing.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/animations/timing'>;
}
declare module 'react-native-reanimated/lib/commonjs/base.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/base'>;
}
declare module 'react-native-reanimated/lib/commonjs/ConfigHelper.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/ConfigHelper'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/__mocks__/AnimatedProps.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/__mocks__/AnimatedProps'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedAlways.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedAlways'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedBezier.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedBezier'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedBlock.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedBlock'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedCall.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedCall'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedCallFunc.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedCallFunc'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedClock.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedClock'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedClockTest.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedClockTest'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedCode.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedCode'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedConcat.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedConcat'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedCond.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedCond'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedDebug.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedDebug'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedEvent.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedEvent'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedFunction.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedFunction'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedNode.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedNode'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedOperator.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedOperator'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedParam.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedParam'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedProps.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedProps'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedSet.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedSet'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedStartClock.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedStartClock'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedStopClock.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedStopClock'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedStyle.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedStyle'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedTransform.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedTransform'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/AnimatedValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/AnimatedValue'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/Core.test.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/Core.test'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/createEventObjectProxyPolyfill.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/createEventObjectProxyPolyfill'>;
}
declare module 'react-native-reanimated/lib/commonjs/core/InternalAnimatedValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/core/InternalAnimatedValue'>;
}
declare module 'react-native-reanimated/lib/commonjs/createAnimatedComponent.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/createAnimatedComponent'>;
}
declare module 'react-native-reanimated/lib/commonjs/derived/__mocks__/evaluateOnce.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/derived/__mocks__/evaluateOnce'>;
}
declare module 'react-native-reanimated/lib/commonjs/derived/acc.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/derived/acc'>;
}
declare module 'react-native-reanimated/lib/commonjs/derived/color.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/derived/color'>;
}
declare module 'react-native-reanimated/lib/commonjs/derived/diff.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/derived/diff'>;
}
declare module 'react-native-reanimated/lib/commonjs/derived/diffClamp.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/derived/diffClamp'>;
}
declare module 'react-native-reanimated/lib/commonjs/derived/evaluateOnce.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/derived/evaluateOnce'>;
}
declare module 'react-native-reanimated/lib/commonjs/derived/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/derived'>;
}
declare module 'react-native-reanimated/lib/commonjs/derived/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/derived'>;
}
declare module 'react-native-reanimated/lib/commonjs/derived/interpolate.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/derived/interpolate'>;
}
declare module 'react-native-reanimated/lib/commonjs/derived/interpolate.test.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/derived/interpolate.test'>;
}
declare module 'react-native-reanimated/lib/commonjs/derived/interpolateColors.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/derived/interpolateColors'>;
}
declare module 'react-native-reanimated/lib/commonjs/derived/onChange.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/derived/onChange'>;
}
declare module 'react-native-reanimated/lib/commonjs/derived/useCode.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/derived/useCode'>;
}
declare module 'react-native-reanimated/lib/commonjs/Easing.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/Easing'>;
}
declare module 'react-native-reanimated/lib/commonjs/operators.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/operators'>;
}
declare module 'react-native-reanimated/lib/commonjs/ReanimatedEventEmitter.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/ReanimatedEventEmitter'>;
}
declare module 'react-native-reanimated/lib/commonjs/ReanimatedModule.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/ReanimatedModule'>;
}
declare module 'react-native-reanimated/lib/commonjs/ReanimatedModule.macos.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/ReanimatedModule.macos'>;
}
declare module 'react-native-reanimated/lib/commonjs/ReanimatedModule.native.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/ReanimatedModule.native'>;
}
declare module 'react-native-reanimated/lib/commonjs/ReanimatedModule.windows.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/ReanimatedModule.windows'>;
}
declare module 'react-native-reanimated/lib/commonjs/ReanimatedModuleCompat.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/ReanimatedModuleCompat'>;
}
declare module 'react-native-reanimated/lib/commonjs/SpringConfig.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/SpringConfig'>;
}
declare module 'react-native-reanimated/lib/commonjs/Transitioning.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/Transitioning'>;
}
declare module 'react-native-reanimated/lib/commonjs/useValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/useValue'>;
}
declare module 'react-native-reanimated/lib/commonjs/val.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/commonjs/val'>;
}
declare module 'react-native-reanimated/lib/module/__mocks__/ReanimatedEventEmitter.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/__mocks__/ReanimatedEventEmitter'>;
}
declare module 'react-native-reanimated/lib/module/__mocks__/ReanimatedModule.native.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/__mocks__/ReanimatedModule.native'>;
}
declare module 'react-native-reanimated/lib/module/Animated.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/Animated'>;
}
declare module 'react-native-reanimated/lib/module/Animated.test.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/Animated.test'>;
}
declare module 'react-native-reanimated/lib/module/animations/Animation.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/animations/Animation'>;
}
declare module 'react-native-reanimated/lib/module/animations/backwardCompatibleAnimWrapper.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/animations/backwardCompatibleAnimWrapper'>;
}
declare module 'react-native-reanimated/lib/module/animations/decay.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/animations/decay'>;
}
declare module 'react-native-reanimated/lib/module/animations/spring.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/animations/spring'>;
}
declare module 'react-native-reanimated/lib/module/animations/SpringUtils.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/animations/SpringUtils'>;
}
declare module 'react-native-reanimated/lib/module/animations/timing.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/animations/timing'>;
}
declare module 'react-native-reanimated/lib/module/base.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/base'>;
}
declare module 'react-native-reanimated/lib/module/ConfigHelper.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/ConfigHelper'>;
}
declare module 'react-native-reanimated/lib/module/core/__mocks__/AnimatedProps.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/__mocks__/AnimatedProps'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedAlways.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedAlways'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedBezier.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedBezier'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedBlock.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedBlock'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedCall.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedCall'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedCallFunc.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedCallFunc'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedClock.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedClock'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedClockTest.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedClockTest'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedCode.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedCode'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedConcat.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedConcat'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedCond.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedCond'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedDebug.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedDebug'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedEvent.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedEvent'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedFunction.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedFunction'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedNode.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedNode'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedOperator.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedOperator'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedParam.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedParam'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedProps.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedProps'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedSet.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedSet'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedStartClock.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedStartClock'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedStopClock.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedStopClock'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedStyle.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedStyle'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedTransform.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedTransform'>;
}
declare module 'react-native-reanimated/lib/module/core/AnimatedValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/AnimatedValue'>;
}
declare module 'react-native-reanimated/lib/module/core/Core.test.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/Core.test'>;
}
declare module 'react-native-reanimated/lib/module/core/createEventObjectProxyPolyfill.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/createEventObjectProxyPolyfill'>;
}
declare module 'react-native-reanimated/lib/module/core/InternalAnimatedValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/core/InternalAnimatedValue'>;
}
declare module 'react-native-reanimated/lib/module/createAnimatedComponent.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/createAnimatedComponent'>;
}
declare module 'react-native-reanimated/lib/module/derived/__mocks__/evaluateOnce.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/derived/__mocks__/evaluateOnce'>;
}
declare module 'react-native-reanimated/lib/module/derived/acc.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/derived/acc'>;
}
declare module 'react-native-reanimated/lib/module/derived/color.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/derived/color'>;
}
declare module 'react-native-reanimated/lib/module/derived/diff.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/derived/diff'>;
}
declare module 'react-native-reanimated/lib/module/derived/diffClamp.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/derived/diffClamp'>;
}
declare module 'react-native-reanimated/lib/module/derived/evaluateOnce.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/derived/evaluateOnce'>;
}
declare module 'react-native-reanimated/lib/module/derived/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/derived'>;
}
declare module 'react-native-reanimated/lib/module/derived/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/derived'>;
}
declare module 'react-native-reanimated/lib/module/derived/interpolate.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/derived/interpolate'>;
}
declare module 'react-native-reanimated/lib/module/derived/interpolate.test.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/derived/interpolate.test'>;
}
declare module 'react-native-reanimated/lib/module/derived/interpolateColors.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/derived/interpolateColors'>;
}
declare module 'react-native-reanimated/lib/module/derived/onChange.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/derived/onChange'>;
}
declare module 'react-native-reanimated/lib/module/derived/useCode.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/derived/useCode'>;
}
declare module 'react-native-reanimated/lib/module/Easing.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/Easing'>;
}
declare module 'react-native-reanimated/lib/module/operators.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/operators'>;
}
declare module 'react-native-reanimated/lib/module/ReanimatedEventEmitter.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/ReanimatedEventEmitter'>;
}
declare module 'react-native-reanimated/lib/module/ReanimatedModule.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/ReanimatedModule'>;
}
declare module 'react-native-reanimated/lib/module/ReanimatedModule.macos.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/ReanimatedModule.macos'>;
}
declare module 'react-native-reanimated/lib/module/ReanimatedModule.native.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/ReanimatedModule.native'>;
}
declare module 'react-native-reanimated/lib/module/ReanimatedModule.windows.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/ReanimatedModule.windows'>;
}
declare module 'react-native-reanimated/lib/module/ReanimatedModuleCompat.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/ReanimatedModuleCompat'>;
}
declare module 'react-native-reanimated/lib/module/SpringConfig.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/SpringConfig'>;
}
declare module 'react-native-reanimated/lib/module/Transitioning.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/Transitioning'>;
}
declare module 'react-native-reanimated/lib/module/useValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/useValue'>;
}
declare module 'react-native-reanimated/lib/module/val.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/module/val'>;
}
declare module 'react-native-reanimated/mock.js' {
  declare module.exports: $Exports<'react-native-reanimated/mock'>;
}
declare module 'react-native-reanimated/src/__mocks__/ReanimatedEventEmitter.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/__mocks__/ReanimatedEventEmitter'>;
}
declare module 'react-native-reanimated/src/__mocks__/ReanimatedModule.native.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/__mocks__/ReanimatedModule.native'>;
}
declare module 'react-native-reanimated/src/Animated.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/Animated'>;
}
declare module 'react-native-reanimated/src/Animated.test.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/Animated.test'>;
}
declare module 'react-native-reanimated/src/animations/Animation.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/animations/Animation'>;
}
declare module 'react-native-reanimated/src/animations/backwardCompatibleAnimWrapper.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/animations/backwardCompatibleAnimWrapper'>;
}
declare module 'react-native-reanimated/src/animations/decay.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/animations/decay'>;
}
declare module 'react-native-reanimated/src/animations/spring.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/animations/spring'>;
}
declare module 'react-native-reanimated/src/animations/SpringUtils.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/animations/SpringUtils'>;
}
declare module 'react-native-reanimated/src/animations/timing.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/animations/timing'>;
}
declare module 'react-native-reanimated/src/base.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/base'>;
}
declare module 'react-native-reanimated/src/ConfigHelper.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/ConfigHelper'>;
}
declare module 'react-native-reanimated/src/core/__mocks__/AnimatedProps.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/__mocks__/AnimatedProps'>;
}
declare module 'react-native-reanimated/src/core/AnimatedAlways.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedAlways'>;
}
declare module 'react-native-reanimated/src/core/AnimatedBezier.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedBezier'>;
}
declare module 'react-native-reanimated/src/core/AnimatedBlock.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedBlock'>;
}
declare module 'react-native-reanimated/src/core/AnimatedCall.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedCall'>;
}
declare module 'react-native-reanimated/src/core/AnimatedCallFunc.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedCallFunc'>;
}
declare module 'react-native-reanimated/src/core/AnimatedClock.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedClock'>;
}
declare module 'react-native-reanimated/src/core/AnimatedClockTest.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedClockTest'>;
}
declare module 'react-native-reanimated/src/core/AnimatedCode.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedCode'>;
}
declare module 'react-native-reanimated/src/core/AnimatedConcat.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedConcat'>;
}
declare module 'react-native-reanimated/src/core/AnimatedCond.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedCond'>;
}
declare module 'react-native-reanimated/src/core/AnimatedDebug.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedDebug'>;
}
declare module 'react-native-reanimated/src/core/AnimatedEvent.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedEvent'>;
}
declare module 'react-native-reanimated/src/core/AnimatedFunction.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedFunction'>;
}
declare module 'react-native-reanimated/src/core/AnimatedNode.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedNode'>;
}
declare module 'react-native-reanimated/src/core/AnimatedOperator.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedOperator'>;
}
declare module 'react-native-reanimated/src/core/AnimatedParam.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedParam'>;
}
declare module 'react-native-reanimated/src/core/AnimatedProps.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedProps'>;
}
declare module 'react-native-reanimated/src/core/AnimatedSet.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedSet'>;
}
declare module 'react-native-reanimated/src/core/AnimatedStartClock.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedStartClock'>;
}
declare module 'react-native-reanimated/src/core/AnimatedStopClock.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedStopClock'>;
}
declare module 'react-native-reanimated/src/core/AnimatedStyle.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedStyle'>;
}
declare module 'react-native-reanimated/src/core/AnimatedTransform.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedTransform'>;
}
declare module 'react-native-reanimated/src/core/AnimatedValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/AnimatedValue'>;
}
declare module 'react-native-reanimated/src/core/Core.test.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/Core.test'>;
}
declare module 'react-native-reanimated/src/core/createEventObjectProxyPolyfill.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/createEventObjectProxyPolyfill'>;
}
declare module 'react-native-reanimated/src/core/InternalAnimatedValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/core/InternalAnimatedValue'>;
}
declare module 'react-native-reanimated/src/createAnimatedComponent.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/createAnimatedComponent'>;
}
declare module 'react-native-reanimated/src/derived/__mocks__/evaluateOnce.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/derived/__mocks__/evaluateOnce'>;
}
declare module 'react-native-reanimated/src/derived/acc.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/derived/acc'>;
}
declare module 'react-native-reanimated/src/derived/color.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/derived/color'>;
}
declare module 'react-native-reanimated/src/derived/diff.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/derived/diff'>;
}
declare module 'react-native-reanimated/src/derived/diffClamp.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/derived/diffClamp'>;
}
declare module 'react-native-reanimated/src/derived/evaluateOnce.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/derived/evaluateOnce'>;
}
declare module 'react-native-reanimated/src/derived/index' {
  declare module.exports: $Exports<'react-native-reanimated/src/derived'>;
}
declare module 'react-native-reanimated/src/derived/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/derived'>;
}
declare module 'react-native-reanimated/src/derived/interpolate.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/derived/interpolate'>;
}
declare module 'react-native-reanimated/src/derived/interpolate.test.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/derived/interpolate.test'>;
}
declare module 'react-native-reanimated/src/derived/interpolateColors.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/derived/interpolateColors'>;
}
declare module 'react-native-reanimated/src/derived/onChange.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/derived/onChange'>;
}
declare module 'react-native-reanimated/src/derived/useCode.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/derived/useCode'>;
}
declare module 'react-native-reanimated/src/Easing.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/Easing'>;
}
declare module 'react-native-reanimated/src/operators.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/operators'>;
}
declare module 'react-native-reanimated/src/ReanimatedEventEmitter.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/ReanimatedEventEmitter'>;
}
declare module 'react-native-reanimated/src/ReanimatedModule.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/ReanimatedModule'>;
}
declare module 'react-native-reanimated/src/ReanimatedModule.macos.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/ReanimatedModule.macos'>;
}
declare module 'react-native-reanimated/src/ReanimatedModule.native.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/ReanimatedModule.native'>;
}
declare module 'react-native-reanimated/src/ReanimatedModule.windows.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/ReanimatedModule.windows'>;
}
declare module 'react-native-reanimated/src/ReanimatedModuleCompat.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/ReanimatedModuleCompat'>;
}
declare module 'react-native-reanimated/src/SpringConfig.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/SpringConfig'>;
}
declare module 'react-native-reanimated/src/Transitioning.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/Transitioning'>;
}
declare module 'react-native-reanimated/src/useValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/useValue'>;
}
declare module 'react-native-reanimated/src/val.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/val'>;
}
