// flow-typed signature: afa7c2e413c64335170aa8cf812d2dfc
// flow-typed version: <<STUB>>/react-native-screens_v^2.9.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-screens'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-screens' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-screens/lib/commonjs/createNativeStackNavigator' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/index.d' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/index.native' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack/navigators/createNativeStackNavigator' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack/types' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack/views/HeaderConfig' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack/views/NativeStackView' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/createNativeStackNavigator' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/index.d' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/index.native' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack/navigators/createNativeStackNavigator' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack/types' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack/views/HeaderConfig' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack/views/NativeStackView' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/createNativeStackNavigator' {
  declare module.exports: any;
}

declare module 'react-native-screens/src' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/index.native' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-screens/lib/commonjs/createNativeStackNavigator.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/createNativeStackNavigator'>;
}
declare module 'react-native-screens/lib/commonjs/index.d.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/index.d'>;
}
declare module 'react-native-screens/lib/commonjs/index' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs'>;
}
declare module 'react-native-screens/lib/commonjs/index.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs'>;
}
declare module 'react-native-screens/lib/commonjs/index.native.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/index.native'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/index' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/index.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/navigators/createNativeStackNavigator.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack/navigators/createNativeStackNavigator'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/types.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack/types'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/views/HeaderConfig.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack/views/HeaderConfig'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/views/NativeStackView.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack/views/NativeStackView'>;
}
declare module 'react-native-screens/lib/module/createNativeStackNavigator.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/createNativeStackNavigator'>;
}
declare module 'react-native-screens/lib/module/index.d.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/index.d'>;
}
declare module 'react-native-screens/lib/module/index' {
  declare module.exports: $Exports<'react-native-screens/lib/module'>;
}
declare module 'react-native-screens/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module'>;
}
declare module 'react-native-screens/lib/module/index.native.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/index.native'>;
}
declare module 'react-native-screens/lib/module/native-stack/index' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack'>;
}
declare module 'react-native-screens/lib/module/native-stack/index.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack'>;
}
declare module 'react-native-screens/lib/module/native-stack/navigators/createNativeStackNavigator.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack/navigators/createNativeStackNavigator'>;
}
declare module 'react-native-screens/lib/module/native-stack/types.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack/types'>;
}
declare module 'react-native-screens/lib/module/native-stack/views/HeaderConfig.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack/views/HeaderConfig'>;
}
declare module 'react-native-screens/lib/module/native-stack/views/NativeStackView.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack/views/NativeStackView'>;
}
declare module 'react-native-screens/src/createNativeStackNavigator.js' {
  declare module.exports: $Exports<'react-native-screens/src/createNativeStackNavigator'>;
}
declare module 'react-native-screens/src/index' {
  declare module.exports: $Exports<'react-native-screens/src'>;
}
declare module 'react-native-screens/src/index.js' {
  declare module.exports: $Exports<'react-native-screens/src'>;
}
declare module 'react-native-screens/src/index.native.js' {
  declare module.exports: $Exports<'react-native-screens/src/index.native'>;
}
