// flow-typed signature: 486241ec96899a3a33d5b37069da5c09
// flow-typed version: <<STUB>>/react-native-expo-viewport-units_v^0.0.8/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-expo-viewport-units'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-expo-viewport-units' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-expo-viewport-units/index' {
  declare module.exports: $Exports<'react-native-expo-viewport-units'>;
}
declare module 'react-native-expo-viewport-units/index.js' {
  declare module.exports: $Exports<'react-native-expo-viewport-units'>;
}
