// flow-typed signature: 35df8f0cb3d1558b870e5ec8b7608129
// flow-typed version: <<STUB>>/storybook_v^5.3.19/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'storybook/index' {
  declare module.exports: $Exports<'storybook'>;
}
declare module 'storybook/index.js' {
  declare module.exports: $Exports<'storybook'>;
}
