// flow-typed signature: befda204c14feb8ccf64e96352b412d1
// flow-typed version: <<STUB>>/world-countries_v^4.0.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'world-countries'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'world-countries' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'world-countries/index' {
  declare module.exports: $Exports<'world-countries'>;
}
declare module 'world-countries/index.js' {
  declare module.exports: $Exports<'world-countries'>;
}
