// flow-typed signature: 3d83ff4a96d8802d4c639e3e65c4b85d
// flow-typed version: <<STUB>>/@react-native-community/picker_v^1.6.5/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/picker/babel.config' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/jest.setup' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/js/AndroidDialogPickerNativeComponent' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/js' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/js/Picker' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/js/Picker.web' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/js/PickerAndroid.android' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/js/PickerAndroid.ios' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/js/PickerAndroid.windows' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/js/PickerIOS.android' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/js/PickerIOS.ios' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/js/PickerIOS.web' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/js/PickerIOS.windows' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/js/PickerItem' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/js/PickerWindows' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/js/PickerWindows.windows' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/js/RNCPickerNativeComponent' {
  declare module.exports: any;
}

declare module '@react-native-community/picker/react-native.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/picker/babel.config.js' {
  declare module.exports: $Exports<'@react-native-community/picker/babel.config'>;
}
declare module '@react-native-community/picker/index' {
  declare module.exports: $Exports<'@react-native-community/picker'>;
}
declare module '@react-native-community/picker/index.js' {
  declare module.exports: $Exports<'@react-native-community/picker'>;
}
declare module '@react-native-community/picker/jest.setup.js' {
  declare module.exports: $Exports<'@react-native-community/picker/jest.setup'>;
}
declare module '@react-native-community/picker/js/AndroidDialogPickerNativeComponent.js' {
  declare module.exports: $Exports<'@react-native-community/picker/js/AndroidDialogPickerNativeComponent'>;
}
declare module '@react-native-community/picker/js/index' {
  declare module.exports: $Exports<'@react-native-community/picker/js'>;
}
declare module '@react-native-community/picker/js/index.js' {
  declare module.exports: $Exports<'@react-native-community/picker/js'>;
}
declare module '@react-native-community/picker/js/Picker.js' {
  declare module.exports: $Exports<'@react-native-community/picker/js/Picker'>;
}
declare module '@react-native-community/picker/js/Picker.web.js' {
  declare module.exports: $Exports<'@react-native-community/picker/js/Picker.web'>;
}
declare module '@react-native-community/picker/js/PickerAndroid.android.js' {
  declare module.exports: $Exports<'@react-native-community/picker/js/PickerAndroid.android'>;
}
declare module '@react-native-community/picker/js/PickerAndroid.ios.js' {
  declare module.exports: $Exports<'@react-native-community/picker/js/PickerAndroid.ios'>;
}
declare module '@react-native-community/picker/js/PickerAndroid.windows.js' {
  declare module.exports: $Exports<'@react-native-community/picker/js/PickerAndroid.windows'>;
}
declare module '@react-native-community/picker/js/PickerIOS.android.js' {
  declare module.exports: $Exports<'@react-native-community/picker/js/PickerIOS.android'>;
}
declare module '@react-native-community/picker/js/PickerIOS.ios.js' {
  declare module.exports: $Exports<'@react-native-community/picker/js/PickerIOS.ios'>;
}
declare module '@react-native-community/picker/js/PickerIOS.web.js' {
  declare module.exports: $Exports<'@react-native-community/picker/js/PickerIOS.web'>;
}
declare module '@react-native-community/picker/js/PickerIOS.windows.js' {
  declare module.exports: $Exports<'@react-native-community/picker/js/PickerIOS.windows'>;
}
declare module '@react-native-community/picker/js/PickerItem.js' {
  declare module.exports: $Exports<'@react-native-community/picker/js/PickerItem'>;
}
declare module '@react-native-community/picker/js/PickerWindows.js' {
  declare module.exports: $Exports<'@react-native-community/picker/js/PickerWindows'>;
}
declare module '@react-native-community/picker/js/PickerWindows.windows.js' {
  declare module.exports: $Exports<'@react-native-community/picker/js/PickerWindows.windows'>;
}
declare module '@react-native-community/picker/js/RNCPickerNativeComponent.js' {
  declare module.exports: $Exports<'@react-native-community/picker/js/RNCPickerNativeComponent'>;
}
declare module '@react-native-community/picker/react-native.config.js' {
  declare module.exports: $Exports<'@react-native-community/picker/react-native.config'>;
}
