// flow-typed signature: 264a206b6afc2d1998eafdfb0ebb120b
// flow-typed version: <<STUB>>/@react-native-community/slider_v^3.0.3/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/slider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/slider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/slider/babel.config' {
  declare module.exports: any;
}

declare module '@react-native-community/slider/dist/__tests__/Slider.test' {
  declare module.exports: any;
}

declare module '@react-native-community/slider/dist/RNCSliderNativeComponent' {
  declare module.exports: any;
}

declare module '@react-native-community/slider/dist/RNCSliderNativeComponent.web' {
  declare module.exports: any;
}

declare module '@react-native-community/slider/dist/Slider' {
  declare module.exports: any;
}

declare module '@react-native-community/slider/js/__tests__/Slider.test' {
  declare module.exports: any;
}

declare module '@react-native-community/slider/js/RNCSliderNativeComponent' {
  declare module.exports: any;
}

declare module '@react-native-community/slider/js/RNCSliderNativeComponent.web' {
  declare module.exports: any;
}

declare module '@react-native-community/slider/js/Slider' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/slider/babel.config.js' {
  declare module.exports: $Exports<'@react-native-community/slider/babel.config'>;
}
declare module '@react-native-community/slider/dist/__tests__/Slider.test.js' {
  declare module.exports: $Exports<'@react-native-community/slider/dist/__tests__/Slider.test'>;
}
declare module '@react-native-community/slider/dist/RNCSliderNativeComponent.js' {
  declare module.exports: $Exports<'@react-native-community/slider/dist/RNCSliderNativeComponent'>;
}
declare module '@react-native-community/slider/dist/RNCSliderNativeComponent.web.js' {
  declare module.exports: $Exports<'@react-native-community/slider/dist/RNCSliderNativeComponent.web'>;
}
declare module '@react-native-community/slider/dist/Slider.js' {
  declare module.exports: $Exports<'@react-native-community/slider/dist/Slider'>;
}
declare module '@react-native-community/slider/js/__tests__/Slider.test.js' {
  declare module.exports: $Exports<'@react-native-community/slider/js/__tests__/Slider.test'>;
}
declare module '@react-native-community/slider/js/RNCSliderNativeComponent.js' {
  declare module.exports: $Exports<'@react-native-community/slider/js/RNCSliderNativeComponent'>;
}
declare module '@react-native-community/slider/js/RNCSliderNativeComponent.web.js' {
  declare module.exports: $Exports<'@react-native-community/slider/js/RNCSliderNativeComponent.web'>;
}
declare module '@react-native-community/slider/js/Slider.js' {
  declare module.exports: $Exports<'@react-native-community/slider/js/Slider'>;
}
