// flow-typed signature: f1491bd3af728daf1483da87f81b3c51
// flow-typed version: <<STUB>>/@react-navigation/bottom-tabs_v5.11.6/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-navigation/bottom-tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-navigation/bottom-tabs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-navigation/bottom-tabs/lib/commonjs/index' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/commonjs/navigators/createBottomTabNavigator' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/commonjs/types' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/commonjs/utils/BottomTabBarHeightCallbackContext' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/commonjs/utils/BottomTabBarHeightContext' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/commonjs/utils/useBottomTabBarHeight' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/commonjs/utils/useIsKeyboardShown' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/commonjs/utils/useWindowDimensions' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/commonjs/views/Badge' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/commonjs/views/BottomTabBar' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/commonjs/views/BottomTabItem' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/commonjs/views/BottomTabView' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/commonjs/views/ResourceSavingScene' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/commonjs/views/SafeAreaProviderCompat' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/commonjs/views/TabBarIcon' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/module/index' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/module/navigators/createBottomTabNavigator' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/module/types' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/module/utils/BottomTabBarHeightCallbackContext' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/module/utils/BottomTabBarHeightContext' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/module/utils/useBottomTabBarHeight' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/module/utils/useIsKeyboardShown' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/module/utils/useWindowDimensions' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/module/views/Badge' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/module/views/BottomTabBar' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/module/views/BottomTabItem' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/module/views/BottomTabView' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/module/views/ResourceSavingScene' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/module/views/SafeAreaProviderCompat' {
  declare module.exports: any;
}

declare module '@react-navigation/bottom-tabs/lib/module/views/TabBarIcon' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-navigation/bottom-tabs/lib/commonjs/index.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/commonjs/index'>;
}
declare module '@react-navigation/bottom-tabs/lib/commonjs/navigators/createBottomTabNavigator.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/commonjs/navigators/createBottomTabNavigator'>;
}
declare module '@react-navigation/bottom-tabs/lib/commonjs/types.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/commonjs/types'>;
}
declare module '@react-navigation/bottom-tabs/lib/commonjs/utils/BottomTabBarHeightCallbackContext.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/commonjs/utils/BottomTabBarHeightCallbackContext'>;
}
declare module '@react-navigation/bottom-tabs/lib/commonjs/utils/BottomTabBarHeightContext.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/commonjs/utils/BottomTabBarHeightContext'>;
}
declare module '@react-navigation/bottom-tabs/lib/commonjs/utils/useBottomTabBarHeight.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/commonjs/utils/useBottomTabBarHeight'>;
}
declare module '@react-navigation/bottom-tabs/lib/commonjs/utils/useIsKeyboardShown.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/commonjs/utils/useIsKeyboardShown'>;
}
declare module '@react-navigation/bottom-tabs/lib/commonjs/utils/useWindowDimensions.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/commonjs/utils/useWindowDimensions'>;
}
declare module '@react-navigation/bottom-tabs/lib/commonjs/views/Badge.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/commonjs/views/Badge'>;
}
declare module '@react-navigation/bottom-tabs/lib/commonjs/views/BottomTabBar.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/commonjs/views/BottomTabBar'>;
}
declare module '@react-navigation/bottom-tabs/lib/commonjs/views/BottomTabItem.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/commonjs/views/BottomTabItem'>;
}
declare module '@react-navigation/bottom-tabs/lib/commonjs/views/BottomTabView.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/commonjs/views/BottomTabView'>;
}
declare module '@react-navigation/bottom-tabs/lib/commonjs/views/ResourceSavingScene.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/commonjs/views/ResourceSavingScene'>;
}
declare module '@react-navigation/bottom-tabs/lib/commonjs/views/SafeAreaProviderCompat.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/commonjs/views/SafeAreaProviderCompat'>;
}
declare module '@react-navigation/bottom-tabs/lib/commonjs/views/TabBarIcon.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/commonjs/views/TabBarIcon'>;
}
declare module '@react-navigation/bottom-tabs/lib/module/index.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/module/index'>;
}
declare module '@react-navigation/bottom-tabs/lib/module/navigators/createBottomTabNavigator.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/module/navigators/createBottomTabNavigator'>;
}
declare module '@react-navigation/bottom-tabs/lib/module/types.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/module/types'>;
}
declare module '@react-navigation/bottom-tabs/lib/module/utils/BottomTabBarHeightCallbackContext.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/module/utils/BottomTabBarHeightCallbackContext'>;
}
declare module '@react-navigation/bottom-tabs/lib/module/utils/BottomTabBarHeightContext.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/module/utils/BottomTabBarHeightContext'>;
}
declare module '@react-navigation/bottom-tabs/lib/module/utils/useBottomTabBarHeight.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/module/utils/useBottomTabBarHeight'>;
}
declare module '@react-navigation/bottom-tabs/lib/module/utils/useIsKeyboardShown.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/module/utils/useIsKeyboardShown'>;
}
declare module '@react-navigation/bottom-tabs/lib/module/utils/useWindowDimensions.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/module/utils/useWindowDimensions'>;
}
declare module '@react-navigation/bottom-tabs/lib/module/views/Badge.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/module/views/Badge'>;
}
declare module '@react-navigation/bottom-tabs/lib/module/views/BottomTabBar.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/module/views/BottomTabBar'>;
}
declare module '@react-navigation/bottom-tabs/lib/module/views/BottomTabItem.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/module/views/BottomTabItem'>;
}
declare module '@react-navigation/bottom-tabs/lib/module/views/BottomTabView.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/module/views/BottomTabView'>;
}
declare module '@react-navigation/bottom-tabs/lib/module/views/ResourceSavingScene.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/module/views/ResourceSavingScene'>;
}
declare module '@react-navigation/bottom-tabs/lib/module/views/SafeAreaProviderCompat.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/module/views/SafeAreaProviderCompat'>;
}
declare module '@react-navigation/bottom-tabs/lib/module/views/TabBarIcon.js' {
  declare module.exports: $Exports<'@react-navigation/bottom-tabs/lib/module/views/TabBarIcon'>;
}
