// flow-typed signature: 25281ef6483fd522aed8f1408571ca03
// flow-typed version: <<STUB>>/@react-navigation/stack_v5.14.1/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-navigation/stack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-navigation/stack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-navigation/stack/lib/commonjs/index' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/navigators/createStackNavigator' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/TransitionConfigs/CardStyleInterpolators' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/TransitionConfigs/HeaderStyleInterpolators' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/TransitionConfigs/TransitionPresets' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/TransitionConfigs/TransitionSpecs' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/types' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/utils/CardAnimationContext' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/utils/conditional' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/utils/debounce' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/utils/GestureHandlerRefContext' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/utils/getDistanceForDirection' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/utils/getInvertedMultiplier' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/utils/HeaderHeightContext' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/utils/HeaderShownContext' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/utils/memoize' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/utils/PreviousSceneContext' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/utils/useCardAnimation' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/utils/useGestureHandlerRef' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/utils/useHeaderHeight' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/BorderlessButton' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/GestureHandler.android' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/GestureHandler.ios' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/GestureHandler' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/GestureHandlerNative' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/Header/Header' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/Header/HeaderBackButton' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/Header/HeaderBackground' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/Header/HeaderContainer' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/Header/HeaderSegment' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/Header/HeaderTitle' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/KeyboardManager' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/MaskedView.android' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/MaskedView.ios' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/MaskedView' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/MaskedViewNative' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/SafeAreaProviderCompat' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/Screens' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/Stack/Card' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/Stack/CardContainer' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/Stack/CardSheet' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/Stack/CardStack' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/Stack/StackView' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/TouchableItem.ios' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/commonjs/views/TouchableItem' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/index' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/navigators/createStackNavigator' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/TransitionConfigs/CardStyleInterpolators' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/TransitionConfigs/HeaderStyleInterpolators' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/TransitionConfigs/TransitionPresets' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/TransitionConfigs/TransitionSpecs' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/types' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/utils/CardAnimationContext' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/utils/conditional' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/utils/debounce' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/utils/GestureHandlerRefContext' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/utils/getDistanceForDirection' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/utils/getInvertedMultiplier' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/utils/HeaderHeightContext' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/utils/HeaderShownContext' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/utils/memoize' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/utils/PreviousSceneContext' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/utils/useCardAnimation' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/utils/useGestureHandlerRef' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/utils/useHeaderHeight' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/BorderlessButton' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/GestureHandler.android' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/GestureHandler.ios' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/GestureHandler' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/GestureHandlerNative' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/Header/Header' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/Header/HeaderBackButton' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/Header/HeaderBackground' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/Header/HeaderContainer' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/Header/HeaderSegment' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/Header/HeaderTitle' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/KeyboardManager' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/MaskedView.android' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/MaskedView.ios' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/MaskedView' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/MaskedViewNative' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/SafeAreaProviderCompat' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/Screens' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/Stack/Card' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/Stack/CardContainer' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/Stack/CardSheet' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/Stack/CardStack' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/Stack/StackView' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/TouchableItem.ios' {
  declare module.exports: any;
}

declare module '@react-navigation/stack/lib/module/views/TouchableItem' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-navigation/stack/lib/commonjs/index.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/index'>;
}
declare module '@react-navigation/stack/lib/commonjs/navigators/createStackNavigator.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/navigators/createStackNavigator'>;
}
declare module '@react-navigation/stack/lib/commonjs/TransitionConfigs/CardStyleInterpolators.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/TransitionConfigs/CardStyleInterpolators'>;
}
declare module '@react-navigation/stack/lib/commonjs/TransitionConfigs/HeaderStyleInterpolators.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/TransitionConfigs/HeaderStyleInterpolators'>;
}
declare module '@react-navigation/stack/lib/commonjs/TransitionConfigs/TransitionPresets.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/TransitionConfigs/TransitionPresets'>;
}
declare module '@react-navigation/stack/lib/commonjs/TransitionConfigs/TransitionSpecs.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/TransitionConfigs/TransitionSpecs'>;
}
declare module '@react-navigation/stack/lib/commonjs/types.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/types'>;
}
declare module '@react-navigation/stack/lib/commonjs/utils/CardAnimationContext.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/utils/CardAnimationContext'>;
}
declare module '@react-navigation/stack/lib/commonjs/utils/conditional.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/utils/conditional'>;
}
declare module '@react-navigation/stack/lib/commonjs/utils/debounce.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/utils/debounce'>;
}
declare module '@react-navigation/stack/lib/commonjs/utils/GestureHandlerRefContext.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/utils/GestureHandlerRefContext'>;
}
declare module '@react-navigation/stack/lib/commonjs/utils/getDistanceForDirection.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/utils/getDistanceForDirection'>;
}
declare module '@react-navigation/stack/lib/commonjs/utils/getInvertedMultiplier.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/utils/getInvertedMultiplier'>;
}
declare module '@react-navigation/stack/lib/commonjs/utils/HeaderHeightContext.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/utils/HeaderHeightContext'>;
}
declare module '@react-navigation/stack/lib/commonjs/utils/HeaderShownContext.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/utils/HeaderShownContext'>;
}
declare module '@react-navigation/stack/lib/commonjs/utils/memoize.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/utils/memoize'>;
}
declare module '@react-navigation/stack/lib/commonjs/utils/PreviousSceneContext.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/utils/PreviousSceneContext'>;
}
declare module '@react-navigation/stack/lib/commonjs/utils/useCardAnimation.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/utils/useCardAnimation'>;
}
declare module '@react-navigation/stack/lib/commonjs/utils/useGestureHandlerRef.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/utils/useGestureHandlerRef'>;
}
declare module '@react-navigation/stack/lib/commonjs/utils/useHeaderHeight.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/utils/useHeaderHeight'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/BorderlessButton.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/BorderlessButton'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/GestureHandler.android.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/GestureHandler.android'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/GestureHandler.ios.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/GestureHandler.ios'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/GestureHandler.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/GestureHandler'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/GestureHandlerNative.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/GestureHandlerNative'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/Header/Header.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/Header/Header'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/Header/HeaderBackButton.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/Header/HeaderBackButton'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/Header/HeaderBackground.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/Header/HeaderBackground'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/Header/HeaderContainer.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/Header/HeaderContainer'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/Header/HeaderSegment.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/Header/HeaderSegment'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/Header/HeaderTitle.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/Header/HeaderTitle'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/KeyboardManager.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/KeyboardManager'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/MaskedView.android.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/MaskedView.android'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/MaskedView.ios.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/MaskedView.ios'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/MaskedView.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/MaskedView'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/MaskedViewNative.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/MaskedViewNative'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/SafeAreaProviderCompat.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/SafeAreaProviderCompat'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/Screens.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/Screens'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/Stack/Card.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/Stack/Card'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/Stack/CardContainer.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/Stack/CardContainer'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/Stack/CardSheet.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/Stack/CardSheet'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/Stack/CardStack.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/Stack/CardStack'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/Stack/StackView.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/Stack/StackView'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/TouchableItem.ios.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/TouchableItem.ios'>;
}
declare module '@react-navigation/stack/lib/commonjs/views/TouchableItem.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/commonjs/views/TouchableItem'>;
}
declare module '@react-navigation/stack/lib/module/index.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/index'>;
}
declare module '@react-navigation/stack/lib/module/navigators/createStackNavigator.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/navigators/createStackNavigator'>;
}
declare module '@react-navigation/stack/lib/module/TransitionConfigs/CardStyleInterpolators.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/TransitionConfigs/CardStyleInterpolators'>;
}
declare module '@react-navigation/stack/lib/module/TransitionConfigs/HeaderStyleInterpolators.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/TransitionConfigs/HeaderStyleInterpolators'>;
}
declare module '@react-navigation/stack/lib/module/TransitionConfigs/TransitionPresets.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/TransitionConfigs/TransitionPresets'>;
}
declare module '@react-navigation/stack/lib/module/TransitionConfigs/TransitionSpecs.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/TransitionConfigs/TransitionSpecs'>;
}
declare module '@react-navigation/stack/lib/module/types.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/types'>;
}
declare module '@react-navigation/stack/lib/module/utils/CardAnimationContext.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/utils/CardAnimationContext'>;
}
declare module '@react-navigation/stack/lib/module/utils/conditional.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/utils/conditional'>;
}
declare module '@react-navigation/stack/lib/module/utils/debounce.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/utils/debounce'>;
}
declare module '@react-navigation/stack/lib/module/utils/GestureHandlerRefContext.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/utils/GestureHandlerRefContext'>;
}
declare module '@react-navigation/stack/lib/module/utils/getDistanceForDirection.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/utils/getDistanceForDirection'>;
}
declare module '@react-navigation/stack/lib/module/utils/getInvertedMultiplier.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/utils/getInvertedMultiplier'>;
}
declare module '@react-navigation/stack/lib/module/utils/HeaderHeightContext.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/utils/HeaderHeightContext'>;
}
declare module '@react-navigation/stack/lib/module/utils/HeaderShownContext.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/utils/HeaderShownContext'>;
}
declare module '@react-navigation/stack/lib/module/utils/memoize.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/utils/memoize'>;
}
declare module '@react-navigation/stack/lib/module/utils/PreviousSceneContext.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/utils/PreviousSceneContext'>;
}
declare module '@react-navigation/stack/lib/module/utils/useCardAnimation.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/utils/useCardAnimation'>;
}
declare module '@react-navigation/stack/lib/module/utils/useGestureHandlerRef.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/utils/useGestureHandlerRef'>;
}
declare module '@react-navigation/stack/lib/module/utils/useHeaderHeight.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/utils/useHeaderHeight'>;
}
declare module '@react-navigation/stack/lib/module/views/BorderlessButton.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/BorderlessButton'>;
}
declare module '@react-navigation/stack/lib/module/views/GestureHandler.android.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/GestureHandler.android'>;
}
declare module '@react-navigation/stack/lib/module/views/GestureHandler.ios.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/GestureHandler.ios'>;
}
declare module '@react-navigation/stack/lib/module/views/GestureHandler.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/GestureHandler'>;
}
declare module '@react-navigation/stack/lib/module/views/GestureHandlerNative.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/GestureHandlerNative'>;
}
declare module '@react-navigation/stack/lib/module/views/Header/Header.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/Header/Header'>;
}
declare module '@react-navigation/stack/lib/module/views/Header/HeaderBackButton.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/Header/HeaderBackButton'>;
}
declare module '@react-navigation/stack/lib/module/views/Header/HeaderBackground.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/Header/HeaderBackground'>;
}
declare module '@react-navigation/stack/lib/module/views/Header/HeaderContainer.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/Header/HeaderContainer'>;
}
declare module '@react-navigation/stack/lib/module/views/Header/HeaderSegment.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/Header/HeaderSegment'>;
}
declare module '@react-navigation/stack/lib/module/views/Header/HeaderTitle.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/Header/HeaderTitle'>;
}
declare module '@react-navigation/stack/lib/module/views/KeyboardManager.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/KeyboardManager'>;
}
declare module '@react-navigation/stack/lib/module/views/MaskedView.android.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/MaskedView.android'>;
}
declare module '@react-navigation/stack/lib/module/views/MaskedView.ios.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/MaskedView.ios'>;
}
declare module '@react-navigation/stack/lib/module/views/MaskedView.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/MaskedView'>;
}
declare module '@react-navigation/stack/lib/module/views/MaskedViewNative.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/MaskedViewNative'>;
}
declare module '@react-navigation/stack/lib/module/views/SafeAreaProviderCompat.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/SafeAreaProviderCompat'>;
}
declare module '@react-navigation/stack/lib/module/views/Screens.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/Screens'>;
}
declare module '@react-navigation/stack/lib/module/views/Stack/Card.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/Stack/Card'>;
}
declare module '@react-navigation/stack/lib/module/views/Stack/CardContainer.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/Stack/CardContainer'>;
}
declare module '@react-navigation/stack/lib/module/views/Stack/CardSheet.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/Stack/CardSheet'>;
}
declare module '@react-navigation/stack/lib/module/views/Stack/CardStack.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/Stack/CardStack'>;
}
declare module '@react-navigation/stack/lib/module/views/Stack/StackView.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/Stack/StackView'>;
}
declare module '@react-navigation/stack/lib/module/views/TouchableItem.ios.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/TouchableItem.ios'>;
}
declare module '@react-navigation/stack/lib/module/views/TouchableItem.js' {
  declare module.exports: $Exports<'@react-navigation/stack/lib/module/views/TouchableItem'>;
}
