/**
 * @format
 * @flow
 */

import {
  FIREBASE_AUTH_EMULATOR_HOST as FIREBASE_AUTH_EMULATOR_HOST_STR,
  FIRESTORE_EMULATOR_HOST as FIRESTORE_EMULATOR_HOST_STR,
  FIRESTORE_EMULATOR_PERSISTENCE as FIRESTORE_EMULATOR_PERSISTENCE_STR,
  GOOGLE_API_KEY as GOOGLE_API_KEY_STR,
  IS_BETA_RELASE as IS_BETA_RELASE_STR,
  JIRA_API_KEY as JIRA_API_KEY_STR,
  JIRA_EMAIL as JIRA_EMAIL_STR,
  JIRA_TICKET_URL as JIRA_TICKET_URL_STR,
  SLACK_WEBHOOK_URL as SLACK_WEBHOOK_URL_STR,
  USE_FIREBASE_EMULATOR as USE_FIREBASE_EMULATOR_STR,
  WEB_APP_BASE as WEB_APP_BASE_STR,
} from '@env'

export const FIREBASE_AUTH_EMULATOR_HOST = FIREBASE_AUTH_EMULATOR_HOST_STR

export const FIRESTORE_EMULATOR_HOST = FIRESTORE_EMULATOR_HOST_STR

export const FIRESTORE_EMULATOR_PERSISTENCE =
  FIRESTORE_EMULATOR_PERSISTENCE_STR === 'true'

export const GOOGLE_API_KEY = GOOGLE_API_KEY_STR

export const IS_BETA_RELASE = IS_BETA_RELASE_STR === 'true'

export const JIRA_API_KEY = JIRA_API_KEY_STR

export const JIRA_EMAIL = JIRA_EMAIL_STR

export const JIRA_TICKET_URL = JIRA_TICKET_URL_STR

export const SLACK_WEBHOOK_URL = SLACK_WEBHOOK_URL_STR

export const USE_FIREBASE_EMULATOR = USE_FIREBASE_EMULATOR_STR === 'true'

export const WEB_APP_BASE = WEB_APP_BASE_STR
