#!/usr/bin/env node
const admin = require('firebase-admin')
const readline = require('readline')

const projectId = 'litten-app'
const usersCollection = 'users'
const commonPassword = 'thisisthepassword'

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
})

admin.initializeApp({ projectId })

const main = async () => {
  const auth = admin.auth()
  const db = admin.firestore()
  const users = db.collection(usersCollection)

  const usersSnapshot = await users.get()
  usersSnapshot.forEach(async (doc) => {
    const user = { ...doc.data(), id: doc.id }

    if (user.email) {
      auth.createUser({
        displayName: user.displayName,
        email: user.email,
        password: commonPassword,
        uid: user.id,
      })
    }
  })

  // Keep firebase emulator alive
  rl.question('Hit CTRL+C to close', () => undefined)
}

main()
