// flow-typed signature: 5f57db4695219fa7b2b44e2c7fb0aa1f
// flow-typed version: <<STUB>>/@react-native-firebase/auth_v^9.0.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-firebase/auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-firebase/auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-firebase/auth/lib/ConfirmationResult' {
  declare module.exports: any;
}

declare module '@react-native-firebase/auth/lib' {
  declare module.exports: any;
}

declare module '@react-native-firebase/auth/lib/PhoneAuthListener' {
  declare module.exports: any;
}

declare module '@react-native-firebase/auth/lib/providers/AppleAuthProvider' {
  declare module.exports: any;
}

declare module '@react-native-firebase/auth/lib/providers/EmailAuthProvider' {
  declare module.exports: any;
}

declare module '@react-native-firebase/auth/lib/providers/FacebookAuthProvider' {
  declare module.exports: any;
}

declare module '@react-native-firebase/auth/lib/providers/GithubAuthProvider' {
  declare module.exports: any;
}

declare module '@react-native-firebase/auth/lib/providers/GoogleAuthProvider' {
  declare module.exports: any;
}

declare module '@react-native-firebase/auth/lib/providers/OAuthProvider' {
  declare module.exports: any;
}

declare module '@react-native-firebase/auth/lib/providers/PhoneAuthProvider' {
  declare module.exports: any;
}

declare module '@react-native-firebase/auth/lib/providers/TwitterAuthProvider' {
  declare module.exports: any;
}

declare module '@react-native-firebase/auth/lib/Settings' {
  declare module.exports: any;
}

declare module '@react-native-firebase/auth/lib/User' {
  declare module.exports: any;
}

declare module '@react-native-firebase/auth/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-firebase/auth/lib/ConfirmationResult.js' {
  declare module.exports: $Exports<'@react-native-firebase/auth/lib/ConfirmationResult'>;
}
declare module '@react-native-firebase/auth/lib/index' {
  declare module.exports: $Exports<'@react-native-firebase/auth/lib'>;
}
declare module '@react-native-firebase/auth/lib/index.js' {
  declare module.exports: $Exports<'@react-native-firebase/auth/lib'>;
}
declare module '@react-native-firebase/auth/lib/PhoneAuthListener.js' {
  declare module.exports: $Exports<'@react-native-firebase/auth/lib/PhoneAuthListener'>;
}
declare module '@react-native-firebase/auth/lib/providers/AppleAuthProvider.js' {
  declare module.exports: $Exports<'@react-native-firebase/auth/lib/providers/AppleAuthProvider'>;
}
declare module '@react-native-firebase/auth/lib/providers/EmailAuthProvider.js' {
  declare module.exports: $Exports<'@react-native-firebase/auth/lib/providers/EmailAuthProvider'>;
}
declare module '@react-native-firebase/auth/lib/providers/FacebookAuthProvider.js' {
  declare module.exports: $Exports<'@react-native-firebase/auth/lib/providers/FacebookAuthProvider'>;
}
declare module '@react-native-firebase/auth/lib/providers/GithubAuthProvider.js' {
  declare module.exports: $Exports<'@react-native-firebase/auth/lib/providers/GithubAuthProvider'>;
}
declare module '@react-native-firebase/auth/lib/providers/GoogleAuthProvider.js' {
  declare module.exports: $Exports<'@react-native-firebase/auth/lib/providers/GoogleAuthProvider'>;
}
declare module '@react-native-firebase/auth/lib/providers/OAuthProvider.js' {
  declare module.exports: $Exports<'@react-native-firebase/auth/lib/providers/OAuthProvider'>;
}
declare module '@react-native-firebase/auth/lib/providers/PhoneAuthProvider.js' {
  declare module.exports: $Exports<'@react-native-firebase/auth/lib/providers/PhoneAuthProvider'>;
}
declare module '@react-native-firebase/auth/lib/providers/TwitterAuthProvider.js' {
  declare module.exports: $Exports<'@react-native-firebase/auth/lib/providers/TwitterAuthProvider'>;
}
declare module '@react-native-firebase/auth/lib/Settings.js' {
  declare module.exports: $Exports<'@react-native-firebase/auth/lib/Settings'>;
}
declare module '@react-native-firebase/auth/lib/User.js' {
  declare module.exports: $Exports<'@react-native-firebase/auth/lib/User'>;
}
declare module '@react-native-firebase/auth/lib/version.js' {
  declare module.exports: $Exports<'@react-native-firebase/auth/lib/version'>;
}
