// flow-typed signature: 838602470e6e9485413e60992d417627
// flow-typed version: <<STUB>>/@react-native-firebase/firestore_v^7.4.3/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-firebase/firestore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-firebase/firestore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-firebase/firestore/lib/FirestoreBlob' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreCollectionReference' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreDocumentChange' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreDocumentReference' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreDocumentSnapshot' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreFieldPath' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreFieldValue' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreGeoPoint' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestorePath' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreQuery' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreQueryModifiers' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreQuerySnapshot' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreSnapshotMetadata' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreStatics' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreTimestamp' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreTransaction' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreTransactionHandler' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/FirestoreWriteBatch' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/utils' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/utils/serialize' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/utils/typemap' {
  declare module.exports: any;
}

declare module '@react-native-firebase/firestore/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-firebase/firestore/lib/FirestoreBlob.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreBlob'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreCollectionReference.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreCollectionReference'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreDocumentChange.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreDocumentChange'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreDocumentReference.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreDocumentReference'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreDocumentSnapshot.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreDocumentSnapshot'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreFieldPath.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreFieldPath'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreFieldValue.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreFieldValue'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreGeoPoint.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreGeoPoint'>;
}
declare module '@react-native-firebase/firestore/lib/FirestorePath.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestorePath'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreQuery.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreQuery'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreQueryModifiers.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreQueryModifiers'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreQuerySnapshot.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreQuerySnapshot'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreSnapshotMetadata.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreSnapshotMetadata'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreStatics.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreStatics'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreTimestamp.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreTimestamp'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreTransaction.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreTransaction'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreTransactionHandler.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreTransactionHandler'>;
}
declare module '@react-native-firebase/firestore/lib/FirestoreWriteBatch.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/FirestoreWriteBatch'>;
}
declare module '@react-native-firebase/firestore/lib/index' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib'>;
}
declare module '@react-native-firebase/firestore/lib/index.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib'>;
}
declare module '@react-native-firebase/firestore/lib/utils/index' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/utils'>;
}
declare module '@react-native-firebase/firestore/lib/utils/index.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/utils'>;
}
declare module '@react-native-firebase/firestore/lib/utils/serialize.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/utils/serialize'>;
}
declare module '@react-native-firebase/firestore/lib/utils/typemap.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/utils/typemap'>;
}
declare module '@react-native-firebase/firestore/lib/version.js' {
  declare module.exports: $Exports<'@react-native-firebase/firestore/lib/version'>;
}
