// flow-typed signature: dd2c71e8a0fc86069800ce788e82a2ae
// flow-typed version: <<STUB>>/@react-native-firebase/storage_v^7.2.2/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-firebase/storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-firebase/storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-firebase/storage/lib' {
  declare module.exports: any;
}

declare module '@react-native-firebase/storage/lib/StorageDownloadTask' {
  declare module.exports: any;
}

declare module '@react-native-firebase/storage/lib/StorageListResult' {
  declare module.exports: any;
}

declare module '@react-native-firebase/storage/lib/StorageReference' {
  declare module.exports: any;
}

declare module '@react-native-firebase/storage/lib/StorageStatics' {
  declare module.exports: any;
}

declare module '@react-native-firebase/storage/lib/StorageTask' {
  declare module.exports: any;
}

declare module '@react-native-firebase/storage/lib/StorageUploadTask' {
  declare module.exports: any;
}

declare module '@react-native-firebase/storage/lib/utils' {
  declare module.exports: any;
}

declare module '@react-native-firebase/storage/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-firebase/storage/lib/index' {
  declare module.exports: $Exports<'@react-native-firebase/storage/lib'>;
}
declare module '@react-native-firebase/storage/lib/index.js' {
  declare module.exports: $Exports<'@react-native-firebase/storage/lib'>;
}
declare module '@react-native-firebase/storage/lib/StorageDownloadTask.js' {
  declare module.exports: $Exports<'@react-native-firebase/storage/lib/StorageDownloadTask'>;
}
declare module '@react-native-firebase/storage/lib/StorageListResult.js' {
  declare module.exports: $Exports<'@react-native-firebase/storage/lib/StorageListResult'>;
}
declare module '@react-native-firebase/storage/lib/StorageReference.js' {
  declare module.exports: $Exports<'@react-native-firebase/storage/lib/StorageReference'>;
}
declare module '@react-native-firebase/storage/lib/StorageStatics.js' {
  declare module.exports: $Exports<'@react-native-firebase/storage/lib/StorageStatics'>;
}
declare module '@react-native-firebase/storage/lib/StorageTask.js' {
  declare module.exports: $Exports<'@react-native-firebase/storage/lib/StorageTask'>;
}
declare module '@react-native-firebase/storage/lib/StorageUploadTask.js' {
  declare module.exports: $Exports<'@react-native-firebase/storage/lib/StorageUploadTask'>;
}
declare module '@react-native-firebase/storage/lib/utils.js' {
  declare module.exports: $Exports<'@react-native-firebase/storage/lib/utils'>;
}
declare module '@react-native-firebase/storage/lib/version.js' {
  declare module.exports: $Exports<'@react-native-firebase/storage/lib/version'>;
}
