// flow-typed signature: 82916014c0f2951454676811b9996288
// flow-typed version: <<STUB>>/@storybook/react-native-server_v^5.3.19/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/react-native-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/react-native-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/react-native-server/bin' {
  declare module.exports: any;
}

declare module '@storybook/react-native-server/dist/client/manager/components/PreviewHelp' {
  declare module.exports: any;
}

declare module '@storybook/react-native-server/dist/client/manager' {
  declare module.exports: any;
}

declare module '@storybook/react-native-server/dist/client/manager/provider' {
  declare module.exports: any;
}

declare module '@storybook/react-native-server/dist/server/cli' {
  declare module.exports: any;
}

declare module '@storybook/react-native-server/dist/server' {
  declare module.exports: any;
}

declare module '@storybook/react-native-server/dist/server/options' {
  declare module.exports: any;
}

declare module '@storybook/react-native-server/dist/server/rn-options-preset' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/react-native-server/bin/index' {
  declare module.exports: $Exports<'@storybook/react-native-server/bin'>;
}
declare module '@storybook/react-native-server/bin/index.js' {
  declare module.exports: $Exports<'@storybook/react-native-server/bin'>;
}
declare module '@storybook/react-native-server/dist/client/manager/components/PreviewHelp.js' {
  declare module.exports: $Exports<'@storybook/react-native-server/dist/client/manager/components/PreviewHelp'>;
}
declare module '@storybook/react-native-server/dist/client/manager/index' {
  declare module.exports: $Exports<'@storybook/react-native-server/dist/client/manager'>;
}
declare module '@storybook/react-native-server/dist/client/manager/index.js' {
  declare module.exports: $Exports<'@storybook/react-native-server/dist/client/manager'>;
}
declare module '@storybook/react-native-server/dist/client/manager/provider.js' {
  declare module.exports: $Exports<'@storybook/react-native-server/dist/client/manager/provider'>;
}
declare module '@storybook/react-native-server/dist/server/cli.js' {
  declare module.exports: $Exports<'@storybook/react-native-server/dist/server/cli'>;
}
declare module '@storybook/react-native-server/dist/server/index' {
  declare module.exports: $Exports<'@storybook/react-native-server/dist/server'>;
}
declare module '@storybook/react-native-server/dist/server/index.js' {
  declare module.exports: $Exports<'@storybook/react-native-server/dist/server'>;
}
declare module '@storybook/react-native-server/dist/server/options.js' {
  declare module.exports: $Exports<'@storybook/react-native-server/dist/server/options'>;
}
declare module '@storybook/react-native-server/dist/server/rn-options-preset.js' {
  declare module.exports: $Exports<'@storybook/react-native-server/dist/server/rn-options-preset'>;
}
