# Drafts the next release notes as pull requests are merged into main
name: Release Drafter

on:
  push:
    branches:
      - next

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.20.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
