# This workflow is manually triggered and will produce the JS bundle source maps
name: Source Maps

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.tag }}
    - name: Use Node.js v14 (LTS)
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - name: Create .env file
      run: cp .env.example .env
    - uses: c-hive/gha-yarn-cache@v1
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Android build
      run: yarn bundle:android
    - name: iOS build
      run: yarn bundle:ios
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-${{ github.event.inputs.tag }}
        path: dist
