# This workflow is manually triggered and will produce the JS bundle source maps
name: Source Maps

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.tag }}
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
    - name: Create .env file
      run: cp .env.example .env
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Android build
      run: yarn bundle:android
    - name: iOS build
      run: yarn bundle:ios
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-${{ github.event.inputs.tag }}
        path: dist
